# 1.4.4 Smoothing Images

## Kernel Convolution

In [1]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

In [2]:
l=1
kernel = np.array([[-0,-1,0],[-1,5,-1],[0,-1,-0]],np.float32)

In [3]:
kernel

array([[ 0., -1.,  0.],
       [-1.,  5., -1.],
       [ 0., -1.,  0.]], dtype=float32)

In [4]:
img = np.random.randint(10, size=(12,12))
#img = np.ones((10,10),np.float32)

In [5]:
img

array([[2, 4, 6, 9, 7, 6, 0, 9, 2, 6, 6, 0],
       [5, 0, 1, 3, 5, 6, 3, 4, 5, 8, 3, 1],
       [7, 1, 5, 2, 3, 1, 0, 1, 9, 6, 2, 6],
       [1, 3, 6, 6, 7, 1, 0, 8, 2, 9, 4, 1],
       [3, 7, 6, 3, 4, 2, 9, 0, 9, 0, 7, 5],
       [9, 4, 8, 5, 9, 1, 0, 2, 2, 7, 8, 1],
       [7, 2, 7, 6, 2, 6, 0, 3, 4, 9, 0, 9],
       [4, 9, 8, 6, 4, 0, 5, 1, 5, 3, 9, 9],
       [2, 2, 2, 3, 7, 3, 6, 3, 8, 0, 7, 8],
       [1, 0, 8, 7, 5, 9, 1, 2, 8, 9, 1, 6],
       [1, 3, 1, 1, 5, 9, 1, 9, 3, 5, 8, 6],
       [1, 1, 0, 3, 9, 0, 2, 9, 2, 7, 1, 0]])

In [6]:
h,w=img.shape

In [7]:
print(h,w)

12 12


In [8]:
#[*range(-2,3)]

In [9]:
dst = np.zeros((h,w),np.int)

C:\Users\kge50\AppData\Local\Temp/ipykernel_13960/2160328971.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dst = np.zeros((h,w),np.int)


In [10]:
for i in range(l,h-l):
    for j in range(l,w-l):
        t=0
        for p in range(-l,l+1):
            for q in range(-l,l+1):
                t += kernel[p+l,q+l]*img[i+p,j+q]
        dst[i,j]=t        

In [11]:
img

array([[2, 4, 6, 9, 7, 6, 0, 9, 2, 6, 6, 0],
       [5, 0, 1, 3, 5, 6, 3, 4, 5, 8, 3, 1],
       [7, 1, 5, 2, 3, 1, 0, 1, 9, 6, 2, 6],
       [1, 3, 6, 6, 7, 1, 0, 8, 2, 9, 4, 1],
       [3, 7, 6, 3, 4, 2, 9, 0, 9, 0, 7, 5],
       [9, 4, 8, 5, 9, 1, 0, 2, 2, 7, 8, 1],
       [7, 2, 7, 6, 2, 6, 0, 3, 4, 9, 0, 9],
       [4, 9, 8, 6, 4, 0, 5, 1, 5, 3, 9, 9],
       [2, 2, 2, 3, 7, 3, 6, 3, 8, 0, 7, 8],
       [1, 0, 8, 7, 5, 9, 1, 2, 8, 9, 1, 6],
       [1, 3, 1, 1, 5, 9, 1, 9, 3, 5, 8, 6],
       [1, 1, 0, 3, 9, 0, 2, 9, 2, 7, 1, 0]])

In [12]:
dst

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0, -11,  -9,  -2,   6,  15,   5,   2,   2,  20,  -2,   0],
       [  0, -10,  15,  -7,   0,  -5,  -5, -16,  31,   2,  -9,   0],
       [  0,   0,  10,  12,  21,  -5, -18,  37, -25,  33,   1,   0],
       [  0,  19,   6,  -6,  -1,  -5,  43, -28,  41, -32,  18,   0],
       [  0,  -6,  18,  -1,  33, -12, -12,   5, -12,  16,  25,   0],
       [  0, -17,  11,  10, -15,  27, -14,   8,   1,  31, -35,   0],
       [  0,  29,  16,   9,   5, -18,  18, -11,   9,  -8,  26,   0],
       [  0,  -3, -11,  -7,  20,  -7,  18,  -2,  24, -27,  17,   0],
       [  0, -14,  30,  18,  -3,  27, -13, -11,  18,  31, -25,   0],
       [  0,  12,  -7, -11,   1,  30, -16,  30,  -9,  -2,  27,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0]])

In [13]:
img = cv2.imread('image\lena.png', 0)

In [14]:
h,w=img.shape

In [ ]:
dst = np.zeros((h-2*l,w-2*l),np.uint8)

In [ ]:
for i in range(l,h-l):
    for j in range(l,w-l):
        t=0
        for p in range(-l,l+1):
            for q in range(-l,l+1):
                t += kernel[p+l,q+l]*img[i+p,j+q]
        dst[i-l,j-l]=t 

In [ ]:
cv2.imshow('img',img)
cv2.imshow('dst',dst)
cv2.waitKey(0)
cv2.destroyAllWindows()